# Generated by Django 5.2.4 on 2025-09-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0003_remove_device_id_device_protocol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[("unknown", "❓"), ("reachable", "✅"), ("unreachable", "❌")],
                default="unknown",
                verbose_name="Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("protocol", "telnet"),
                    ("device_type__endswith", "iosxe"),
                    _negated=True,
                ),
                name="no_telnet_on_iosxe",
                violation_error_message="Telnet is not allowed for IOSXE devices.",
            ),
        ),
    ]
