# Generated by Django 5.2.4 on 2025-09-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_status_device_no_telnet_on_iosxe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
    ]
