# Generated by Django 5.2.8 on 2026-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_id_alter_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='enable_password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
