# Generated by Django 5.2.8 on 2026-01-12 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0006_device_id_alter_device_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="device",
            name="no_telnet_on_iosxe",
        ),
        migrations.AddField(
            model_name="device",
            name="token",
            field=models.CharField(
                blank=True, help_text="FortiGate API Token", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="vendor",
            field=models.CharField(
                choices=[("cisco", "Cisco"), ("fortinet", "Fortinet")],
                default="cisco",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("router_ios", "Router (IOS)"),
                    ("router_iosxe", "Router (IOSXE)"),
                    ("router_iosxr", "Router (IOSXR)"),
                    ("switch_ios", "Switch (IOS)"),
                    ("switch_iosxe", "Switch (IOSXE)"),
                    ("switch_iosxr", "Switch (IOSXR)"),
                ],
                max_length=20,
                null=True,
                verbose_name="Device Type",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="port",
            field=models.IntegerField(
                blank=True,
                default=22,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="protocol",
            field=models.CharField(
                blank=True,
                choices=[("ssh", "SSH"), ("telnet", "Telnet")],
                default="ssh",
                null=True,
                verbose_name="Protocol",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vendor", "cisco"),
                    ("protocol", "telnet"),
                    ("device_type__endswith", "iosxe"),
                    _negated=True,
                ),
                name="no_telnet_on_iosxe",
                violation_error_message="Telnet is not allowed for IOSXE devices.",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vendor", "fortinet"),
                    models.Q(("username__isnull", False), ("password__isnull", False)),
                    _connector="OR",
                ),
                name="cisco_requires_username_password",
                violation_error_message="Cisco devices require username and password.",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vendor", "cisco"), ("token__isnull", False), _connector="OR"
                ),
                name="fortigate_requires_token",
                violation_error_message="FortiGate devices require an API token.",
            ),
        ),
    ]
