# Generated by Django 5.2.8 on 2026-01-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0007_remove_device_no_telnet_on_iosxe_device_token_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="device",
            name="cisco_requires_username_password",
        ),
        migrations.RemoveConstraint(
            model_name="device",
            name="fortigate_requires_token",
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vendor", "cisco"),
                    models.Q(("username__isnull", False), ("password__isnull", False)),
                    _connector="OR",
                ),
                name="cisco_requires_username_password",
                violation_error_message="Cisco devices require username and password.",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vendor", "fortinet"), ("token__isnull", False), _connector="OR"
                ),
                name="fortigate_requires_token",
                violation_error_message="FortiGate devices require an API token.",
            ),
        ),
    ]
