# Generated by Django 5.2.8 on 2026-02-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_enable_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='enable_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
