# Generated by Django 6.0.2 on 2026-03-10 13:17

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_device_enable_password_alter_device_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
