# Generated by Django 5.2.4 on 2025-09-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("networktests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
