# Generated by Django 5.2.4 on 2025-11-04 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_device_status'),
        ('networktests', '0003_alter_testcase_id_alter_testresult_attempt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testdevice',
            name='parent_test_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_parent_parameter', to='networktests.testparameter'),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='parent_test_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_parameter', to='networktests.testparameter'),
        ),
        migrations.AlterField(
            model_name='testdevice',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='testdevice',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='networktests.testcase'),
        ),
        migrations.AlterField(
            model_name='testparameter',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='networktests.testcase'),
        ),
    ]
