# Generated by Django 5.2.8 on 2026-02-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networktests', '0004_testcase_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
