# Generated by Django 5.2.8 on 2026-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networktests', '0005_customtesttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtesttemplate',
            name='file_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
