# Generated by Django 5.2.8 on 2026-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networktests', '0006_add_unique_constraint_to_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtesttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customtesttemplate',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
