# Generated by Django 6.0.2 on 2026-03-10 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_device_enable_password_alter_device_password'),
        ('networktests', '0008_move_testgroup_from_testgroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdevice',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='devices.device'),
        ),
    ]
