"""
Django settings for diagnet project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
import dotenv
from cryptography.fernet import Fernet

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv.load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DIAGNET_DEBUG", "True").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DIAGNET_SECRET_KEY")
if not SECRET_KEY and DEBUG:
    SECRET_KEY = "django-insecure-fallback-key-for-dev-only"

DEVICE_ENCRYPTION_KEY = os.environ.get("DIAGNET_DEVICE_ENCRYPTION_KEY")
if not DEVICE_ENCRYPTION_KEY and DEBUG:
    DEVICE_ENCRYPTION_KEY = "8OGs8CTrNq8TltpMA3H-zybxADNlMt8FvdhEDo0QW98="

if DEVICE_ENCRYPTION_KEY is not None:
    DEVICE_ENCRYPTION_KEY = DEVICE_ENCRYPTION_KEY.encode()


def get_security_help_message(missing_secret, missing_device):
    msg = ["\n" + "=" * 80, "DIAGNET SECURITY CONFIGURATION ERROR", "=" * 80]
    env_suggestions = []

    if missing_secret:
        msg.extend(
            [
                "- MISSING: SECRET_KEY",
                "  This is required for Django's session security.",
            ]
        )
        env_suggestions.append(f'SECRET_KEY="{get_random_secret_key()}"')

    if missing_device:
        msg.extend(
            [
                "- MISSING or INVALID: DEVICE_ENCRYPTION_KEY",
                "  This is required to securely store device passwords.",
                "  It must be a 32-byte url-safe base64-encoded string.",
            ]
        )
        env_suggestions.append(
            f'DEVICE_ENCRYPTION_KEY="{Fernet.generate_key().decode()}"'
        )

    msg.extend(
        [
            "",
            "Recommended .env content (Copy & Paste this block):",
            "--------------------------------------------------",
        ]
    )
    msg.extend(env_suggestions)
    msg.append("--------------------------------------------------")

    msg.extend(
        [
            "=" * 80,
            "1. Open your .env file in the project root.",
            "2. Paste the configuration block above.",
            "3. Save the file and restart the application.",
            "=" * 80 + "\n",
        ]
    )
    return "\n".join(msg)


if not SECRET_KEY or not DEVICE_ENCRYPTION_KEY:
    raise ImproperlyConfigured(
        get_security_help_message(not SECRET_KEY, not DEVICE_ENCRYPTION_KEY)
    )

try:
    Fernet(DEVICE_ENCRYPTION_KEY)
except Exception:
    raise ImproperlyConfigured(get_security_help_message(False, True))


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # our apps
    "accounts.apps.SuperUserSetup",
    "dashboard.apps.DashboardConfig",
    "devices.apps.DevicesConfig",
    "networktests.apps.NetworktestsConfig",
    "testgroups.apps.TestgroupsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "accounts.middleware.SuperuserRequiredMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "diagnet.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "diagnet.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("DIAGNET_DB_PATH", BASE_DIR / "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "accounts": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Authentication
LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
