# Generated by Django 5.2.8 on 2026-01-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('Viewers', 'Viewers - Read Only'), ('Editors', 'Editors - View + Edit/Run'), ('Managers', 'Managers - View + Edit + Delete'), ('Admins', 'Admins - Full Access + User Management')], max_length=20)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group Profile',
                'verbose_name_plural': 'Group Profiles',
            },
        ),
    ]
