# Generated by Django 5.2.4 on 2025-09-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testgroups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testgroup",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
