# Generated by Django 5.2.4 on 2025-09-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networktests', '0002_alter_testcase_id'),
        ('testgroups', '0002_alter_testgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroup',
            name='testcases',
            field=models.ManyToManyField(to='networktests.testcase'),
        ),
    ]
